vpath %.h ./decode
vpath %.c ./decode

source = $(wildcard *.c)
object = $(patsubst %.c,%.o,$(source))
object += decode.o

main: $(object)
	@echo $(object)
	@echo $@
	gcc -o $@ $(object)

.PHONY: clean
clean:
	-rm -f main $(object)


